"""
The 214 Kangxi radicals — the semantic building blocks of Chinese characters.
Learning these first makes every later character decomposable rather than arbitrary.
Common simplified/combining variant forms are noted in the meaning where useful.

Format: (number, radical, pinyin, meaning)
"""

RADICALS = [
    (1, "一", "yī", "one"),
    (2, "丨", "gǔn", "line"),
    (3, "丶", "zhǔ", "dot"),
    (4, "丿", "piě", "slash"),
    (5, "乙", "yǐ", "second (of the ten Heavenly Stems)"),
    (6, "亅", "jué", "hook"),
    (7, "二", "èr", "two"),
    (8, "亠", "tóu", "lid"),
    (9, "人", "rén", "person (also 亻 on the left)"),
    (10, "儿", "ér", "legs"),
    (11, "入", "rù", "enter"),
    (12, "八", "bā", "eight / divide"),
    (13, "冂", "jiōng", "down box / borders"),
    (14, "冖", "mì", "cover"),
    (15, "冫", "bīng", "ice"),
    (16, "几", "jī", "table"),
    (17, "凵", "kǎn", "open box"),
    (18, "刀", "dāo", "knife (also 刂 on the right)"),
    (19, "力", "lì", "power / strength"),
    (20, "勹", "bāo", "wrap"),
    (21, "匕", "bǐ", "spoon / ladle"),
    (22, "匚", "fāng", "right open box"),
    (23, "匸", "xì", "hiding enclosure"),
    (24, "十", "shí", "ten"),
    (25, "卜", "bǔ", "divination"),
    (26, "卩", "jié", "seal (kneeling person)"),
    (27, "厂", "hàn", "cliff"),
    (28, "厶", "sī", "private"),
    (29, "又", "yòu", "again / right hand"),
    (30, "口", "kǒu", "mouth"),
    (31, "囗", "wéi", "enclosure"),
    (32, "土", "tǔ", "earth / soil"),
    (33, "士", "shì", "scholar / soldier"),
    (34, "夂", "zhǐ", "go / follow"),
    (35, "夊", "suī", "go slowly"),
    (36, "夕", "xī", "evening / dusk"),
    (37, "大", "dà", "big"),
    (38, "女", "nǚ", "woman"),
    (39, "子", "zǐ", "child"),
    (40, "宀", "mián", "roof"),
    (41, "寸", "cùn", "inch / thumb"),
    (42, "小", "xiǎo", "small"),
    (43, "尢", "wāng", "lame"),
    (44, "尸", "shī", "corpse / body"),
    (45, "屮", "chè", "sprout"),
    (46, "山", "shān", "mountain"),
    (47, "巛", "chuān", "river (also 川)"),
    (48, "工", "gōng", "work"),
    (49, "己", "jǐ", "oneself"),
    (50, "巾", "jīn", "cloth / turban"),
    (51, "干", "gān", "dry / shield"),
    (52, "幺", "yāo", "short thread / tiny"),
    (53, "广", "guǎng", "dotted cliff / shelter"),
    (54, "廴", "yǐn", "long stride"),
    (55, "廾", "gǒng", "two hands / clasp"),
    (56, "弋", "yì", "shoot / dart"),
    (57, "弓", "gōng", "bow"),
    (58, "彐", "jì", "snout"),
    (59, "彡", "shān", "bristle / hair / rays"),
    (60, "彳", "chì", "step / walk (left)"),
    (61, "心", "xīn", "heart (also 忄 on the left)"),
    (62, "戈", "gē", "halberd / spear"),
    (63, "戶", "hù", "door / household (also 户)"),
    (64, "手", "shǒu", "hand (also 扌 on the left)"),
    (65, "支", "zhī", "branch"),
    (66, "攴", "pū", "rap / tap (also 攵)"),
    (67, "文", "wén", "script / writing"),
    (68, "斗", "dǒu", "dipper / measure"),
    (69, "斤", "jīn", "axe / catty"),
    (70, "方", "fāng", "square / direction"),
    (71, "无", "wú", "not / without"),
    (72, "日", "rì", "sun / day"),
    (73, "曰", "yuē", "say"),
    (74, "月", "yuè", "moon / month (also flesh 肉)"),
    (75, "木", "mù", "tree / wood"),
    (76, "欠", "qiàn", "lack / yawn"),
    (77, "止", "zhǐ", "stop / foot"),
    (78, "歹", "dǎi", "death / bad"),
    (79, "殳", "shū", "weapon / lance"),
    (80, "毋", "wú", "do not"),
    (81, "比", "bǐ", "compare"),
    (82, "毛", "máo", "fur / hair"),
    (83, "氏", "shì", "clan / family"),
    (84, "气", "qì", "steam / air / qi"),
    (85, "水", "shuǐ", "water (also 氵 on the left)"),
    (86, "火", "huǒ", "fire (also 灬 underneath)"),
    (87, "爪", "zhǎo", "claw (also 爫 on top)"),
    (88, "父", "fù", "father"),
    (89, "爻", "yáo", "lines of a trigram"),
    (90, "爿", "qiáng", "split wood (left half)"),
    (91, "片", "piàn", "slice / piece"),
    (92, "牙", "yá", "fang / tooth"),
    (93, "牛", "niú", "cow / ox (also 牜)"),
    (94, "犬", "quǎn", "dog (also 犭 on the left)"),
    (95, "玄", "xuán", "profound / dark"),
    (96, "玉", "yù", "jade (also 王 on the left)"),
    (97, "瓜", "guā", "melon"),
    (98, "瓦", "wǎ", "tile / pottery"),
    (99, "甘", "gān", "sweet"),
    (100, "生", "shēng", "life / grow"),
    (101, "用", "yòng", "use"),
    (102, "田", "tián", "field"),
    (103, "疋", "pǐ", "bolt of cloth / foot"),
    (104, "疒", "nè", "sickness"),
    (105, "癶", "bō", "dotted tent / footsteps"),
    (106, "白", "bái", "white"),
    (107, "皮", "pí", "skin"),
    (108, "皿", "mǐn", "dish / vessel"),
    (109, "目", "mù", "eye"),
    (110, "矛", "máo", "spear / lance"),
    (111, "矢", "shǐ", "arrow"),
    (112, "石", "shí", "stone"),
    (113, "示", "shì", "spirit / altar (also 礻 on the left)"),
    (114, "禸", "róu", "track / footprint"),
    (115, "禾", "hé", "grain / cereal"),
    (116, "穴", "xué", "cave / hole"),
    (117, "立", "lì", "stand"),
    (118, "竹", "zhú", "bamboo (also 𥫗 on top)"),
    (119, "米", "mǐ", "rice"),
    (120, "糸", "mì", "silk / thread (also 纟 simplified)"),
    (121, "缶", "fǒu", "jar / earthenware"),
    (122, "网", "wǎng", "net (also 罒 on top)"),
    (123, "羊", "yáng", "sheep / goat"),
    (124, "羽", "yǔ", "feather / wings"),
    (125, "老", "lǎo", "old (also 耂)"),
    (126, "而", "ér", "and / beard"),
    (127, "耒", "lěi", "plow"),
    (128, "耳", "ěr", "ear"),
    (129, "聿", "yù", "brush / writing"),
    (130, "肉", "ròu", "meat / flesh (also 月 on the left)"),
    (131, "臣", "chén", "minister / official"),
    (132, "自", "zì", "self / nose"),
    (133, "至", "zhì", "arrive / reach"),
    (134, "臼", "jiù", "mortar"),
    (135, "舌", "shé", "tongue"),
    (136, "舛", "chuǎn", "oppose / err"),
    (137, "舟", "zhōu", "boat"),
    (138, "艮", "gèn", "stopping / mountain"),
    (139, "色", "sè", "color"),
    (140, "艸", "cǎo", "grass / plant (also 艹 on top)"),
    (141, "虍", "hū", "tiger stripes"),
    (142, "虫", "chóng", "insect / worm"),
    (143, "血", "xuè", "blood"),
    (144, "行", "xíng", "walk / go"),
    (145, "衣", "yī", "clothes (also 衤 on the left)"),
    (146, "襾", "yà", "cover / west"),
    (147, "見", "jiàn", "see (also 见 simplified)"),
    (148, "角", "jiǎo", "horn"),
    (149, "言", "yán", "speech (also 讠 simplified)"),
    (150, "谷", "gǔ", "valley"),
    (151, "豆", "dòu", "bean / dish"),
    (152, "豕", "shǐ", "pig"),
    (153, "豸", "zhì", "clawed beast"),
    (154, "貝", "bèi", "shell / money (also 贝 simplified)"),
    (155, "赤", "chì", "red"),
    (156, "走", "zǒu", "run / walk"),
    (157, "足", "zú", "foot (also 𧾷)"),
    (158, "身", "shēn", "body"),
    (159, "車", "chē", "cart / vehicle (also 车 simplified)"),
    (160, "辛", "xīn", "bitter / pungent"),
    (161, "辰", "chén", "morning / dragon"),
    (162, "辵", "chuò", "walk / halt (also 辶 on the left)"),
    (163, "邑", "yì", "city (also 阝 on the right)"),
    (164, "酉", "yǒu", "wine vessel / ferment"),
    (165, "釆", "biàn", "distinguish"),
    (166, "里", "lǐ", "village / mile"),
    (167, "金", "jīn", "gold / metal (also 钅 simplified)"),
    (168, "長", "cháng", "long / grow (also 长 simplified)"),
    (169, "門", "mén", "gate / door (also 门 simplified)"),
    (170, "阜", "fù", "mound / hill (also 阝 on the left)"),
    (171, "隶", "lì", "slave / capture"),
    (172, "隹", "zhuī", "short-tailed bird"),
    (173, "雨", "yǔ", "rain"),
    (174, "青", "qīng", "blue / green / young"),
    (175, "非", "fēi", "wrong / not"),
    (176, "面", "miàn", "face"),
    (177, "革", "gé", "leather / hide"),
    (178, "韋", "wéi", "tanned leather (also 韦)"),
    (179, "韭", "jiǔ", "leek"),
    (180, "音", "yīn", "sound"),
    (181, "頁", "yè", "head / page (also 页 simplified)"),
    (182, "風", "fēng", "wind (also 风 simplified)"),
    (183, "飛", "fēi", "fly (also 飞 simplified)"),
    (184, "食", "shí", "eat / food (also 饣 simplified)"),
    (185, "首", "shǒu", "head"),
    (186, "香", "xiāng", "fragrant"),
    (187, "馬", "mǎ", "horse (also 马 simplified)"),
    (188, "骨", "gǔ", "bone"),
    (189, "高", "gāo", "tall / high"),
    (190, "髟", "biāo", "long hair"),
    (191, "鬥", "dòu", "fight"),
    (192, "鬯", "chàng", "sacrificial wine"),
    (193, "鬲", "lì", "cauldron"),
    (194, "鬼", "guǐ", "ghost / spirit"),
    (195, "魚", "yú", "fish (also 鱼 simplified)"),
    (196, "鳥", "niǎo", "bird (also 鸟 simplified)"),
    (197, "鹵", "lǔ", "salt"),
    (198, "鹿", "lù", "deer"),
    (199, "麥", "mài", "wheat (also 麦 simplified)"),
    (200, "麻", "má", "hemp"),
    (201, "黃", "huáng", "yellow"),
    (202, "黍", "shǔ", "millet"),
    (203, "黑", "hēi", "black"),
    (204, "黹", "zhǐ", "embroidery"),
    (205, "黽", "mǐn", "frog / toad"),
    (206, "鼎", "dǐng", "tripod cauldron"),
    (207, "鼓", "gǔ", "drum"),
    (208, "鼠", "shǔ", "rat / mouse"),
    (209, "鼻", "bí", "nose"),
    (210, "齊", "qí", "even / uniform (also 齐)"),
    (211, "齒", "chǐ", "tooth (also 齿 simplified)"),
    (212, "龍", "lóng", "dragon (also 龙 simplified)"),
    (213, "龜", "guī", "turtle (also 龟 simplified)"),
    (214, "龠", "yuè", "flute"),
]
